### ISSUE TITLE
Uncaught TypeError: Cannot read property 'decorationsById' of undefined

### ISSUE THREAD

**Issue by eduardot42** [atom-minimap/minimap-find-and-replace#10]
[Enter steps to reproduce below:]

1. Open find+replace
2. Go to Settings Page
3. Try to close settings page with keyboard command (cmd+w on Mac or ctrl+w for Linux & Windows, note that closing with the little x button on the tab works)

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [minimap-find-and-replace](https://github.com/atom-minimap/minimap-find-and-replace) package, v4.2.2

### Stack Trace

Uncaught TypeError: Cannot read property 'decorationsById' of undefined

```
At /Users/eduardot/.atom/packages/minimap-find-and-replace/lib/minimap-find-results-view.coffee:19

TypeError: Cannot read property 'decorationsById' of undefined
  at MinimapFindResultsView.destroyDecorations (/Users/eduardot/.atom/packages/minimap-find-and-replace/lib/minimap-find-results-view.coffee:19:7)
  at MinimapFindResultsView.destroy (/Users/eduardot/.atom/packages/minimap-find-and-replace/lib/minimap-find-results-view.coffee:14:8)
  at MinimapFindAndReplaceBinding.module.exports.MinimapFindAndReplaceBinding.deactivate (/Users/eduardot/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace-binding.coffee:57:23)
  at atom-workspace.<anonymous> (/Users/eduardot/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace-binding.coffee:1:1)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
  4x -2:06.9.0 core:move-left (atom-text-editor.editor.mini.is-focused)
  6x -2:02.3.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
     -0:40.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:37.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
 10x -0:34.9.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -0:32.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:31.2.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  3x -0:30.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:29.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:29.3.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  6x -0:28.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:26.3.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -0:25.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:23.3.0 settings-view:open (atom-text-editor.editor.is-focused)
  4x -0:12.9.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.5.0 core:close (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "tron-legacy"
    ],
    "followSymlinks": false,
    "excludeVcsIgnoredPaths": false,
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
atom-xsltransform, v0.8.0
compare-files, v0.6.2
language-fish-shell, v1.0.2
language-log, v0.6.0
line-ending-converter, v1.3.2
linter-coffeescript, v1.0.0
linter-ruby, v1.0.1
linter-xmllint, v0.0.7
minimap, v4.12.3
minimap-bookmarks, v0.1.0
minimap-codeglance, v0.4.0
minimap-find-and-replace, v4.2.2
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.0
minimap-linter, v1.0.0
minimap-pigments, v0.1.3
minimap-selection, v4.3.0
open-terminal-here, v2.0.0
set-syntax, v0.3.0
sort-lines, v0.11.0
sync-settings, v0.6.0
tron-legacy, v0.5.0
xml-formatter, v0.9.1
you-complete-me, v0.6.2

# Dev
No dev packages
```

**Comment by eduardot42** [comment]
Please ignore, updated and now issue is fixed on 0.1.5.
