### ISSUE TITLE
Failed to load the minimap-find-and-replace package

### ISSUE THREAD

**Issue by mshyun** [atom-minimap/minimap-find-and-replace#11]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Unknown Windows Version
**Thrown From**: [minimap-find-and-replace](https://github.com/atom-minimap/minimap-find-and-replace) package, v4.3.0

### Stack Trace

Failed to load the minimap-find-and-replace package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\현민성\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\현민성\.atom\packages\minimap-find-and-replace\lib\minimap-find-and-replace.coffee:4:25)
    at Object.<anonymous> (C:\Users\현민성\.atom\packages\minimap-find-and-replace\lib\minimap-find-and-replace.coffee:122:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\현민성\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.6.1
autocomplete-python, v0.5.4
minimap, v4.13.4
minimap-find-and-replace, v4.3.0
minimap-highlight-selected, v4.3.1
minimap-selection, v4.3.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Thanks for the report, it should no longer occurs as event-kit is no longer a dependency.
