### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

### ISSUE THREAD

**Issue by mpneuried** [atom-minimap/minimap-find-and-replace#12]
[Enter steps to reproduce below:]

Just typing with an active searching pattern and probably triggered by switching the pane ... 

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [minimap-find-and-replace](https://github.com/atom-minimap/minimap-find-and-replace) package, v4.3.1

### Stack Trace

Uncaught TypeError: Cannot read property 'onDidDestroy' of undefined

```
At /Users/mathiaspeter/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace-binding.coffee:54

TypeError: Cannot read property 'onDidDestroy' of undefined
  at MinimapFindAndReplaceBinding.module.exports.MinimapFindAndReplaceBinding.createDecoration (/Users/mathiaspeter/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace-binding.coffee:54:53)
  at MinimapFindAndReplaceBinding.module.exports.MinimapFindAndReplaceBinding.handleCreatedMarker (/Users/mathiaspeter/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace-binding.coffee:43:6)
  at /Users/mathiaspeter/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace-binding.coffee:15:8
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at DisplayBuffer.module.exports.DisplayBuffer.handleBufferMarkerCreated (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1715:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.markerCreated (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1354:20)
  at MarkerStore.module.exports.MarkerStore.createMarker (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:332:21)
  at MarkerStore.module.exports.MarkerStore.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:149:19)
  at TextBuffer.module.exports.TextBuffer.markRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:695:31)
  at DisplayBuffer.module.exports.DisplayBuffer.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1403:41)
  at TextEditor.module.exports.TextEditor.markBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1285:59)
  at BufferSearch.module.exports.BufferSearch.createMarker (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:290:28)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:160:46
  at TextBuffer.module.exports.TextBuffer.scanInRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:866:9)
  at TextEditor.module.exports.TextEditor.scanInBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2143:26)
  at BufferSearch.module.exports.BufferSearch.createMarkers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:155:23)
  at BufferSearch.module.exports.BufferSearch.bufferStoppedChanging (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/find-and-replace/lib/buffer-search.js:221:27)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1273:25

```

### Commands

```
  4x -0:57.4.0 core:select-left (atom-text-editor.editor.is-focused)
  2x -0:46.5.0 find-and-replace:select-next (atom-text-editor.editor.is-focused)
     -0:44.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:39.6.0 core:copy (atom-text-editor.editor.is-focused)
     -0:36.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:36.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:18.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:14.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:14.4.0 refactor:done (atom-text-editor.editor.is-focused)
     -0:14.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:14.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:14.2.0 refactor:done (atom-text-editor.editor.is-focused)
     -0:14.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:14.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:14 core:paste (atom-text-editor.editor.is-focused)
  3x -0:08.6.0 core:move-left (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "language-toml",
      "language-sass",
      "language-ruby-on-rails",
      "language-ruby",
      "language-php",
      "language-perl",
      "language-objective-c",
      "language-java",
      "language-csharp",
      "coffee-navigator",
      "term",
      "grunt-runner",
      "inc-dec-value",
      "coffee-eval",
      "metrics",
      "welcome",
      "auto-detect-indentation",
      "atomatigit",
      "git-log",
      "indentation-indicator",
      "coffee-refactor",
      "atom-runner"
    ],
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
atom-beautify, v0.28.15
autocomplete-paths, v1.0.2
coffee-compile, v0.19.2
color-picker, v2.0.13
custom-title, v1.0.1
editorconfig, v1.2.0
emmet, v2.3.13
figlet, v0.5.2
highlight-selected, v0.10.1
js-refactor, v0.6.0
language-diff, v0.3.1
language-docker, v1.1.3
language-jade, v0.6.2
language-nginx, v0.6.1
language-nunjucks, v2.0.0
language-soy, v0.3.0
linter, v1.9.1
linter-coffeelint, v1.1.2
minimap, v4.15.0
minimap-autohide, v0.10.1
minimap-find-and-replace, v4.3.1
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.0.0
minimap-pigments, v0.1.7
pigments, v0.18.0
refactor, v0.6.0
seti-syntax, v0.4.0
seti-ui, v0.8.0
sync-settings, v0.6.0
travis-ci-status, v0.18.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hi @mpneuried, thanks for the report, I'll take a look at that soon.
