### ISSUE TITLE
Uncaught TypeError: Cannot read property 'metadata' of undefined

### ISSUE THREAD

**Issue by EnterpriseBranding** [atom-minimap/minimap-find-and-replace#16]
I'm new to Brackets, but I get the following. Let me know anything I can do. I liked this find and replace better than the other one available, but it's giving me errors (which are below).

[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.4.1
**System**: Mac OS X 10.10.5
**Thrown From**: [minimap-find-and-replace](https://github.com/atom-minimap/minimap-find-and-replace) package, v4.4.0
### Stack Trace

Uncaught TypeError: Cannot read property 'metadata' of undefined

```
At /Users/noahjchampion/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace.coffee:26

TypeError: Cannot read property 'metadata' of undefined
    at Object.module.exports.activatePlugin (/Users/noahjchampion/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace.coffee:26:68)
    at Main.updatesPluginActivationState (/Users/noahjchampion/.atom/packages/minimap/lib/mixins/plugin-management.js:158:14)
    at /Users/noahjchampion/.atom/packages/minimap/lib/mixins/plugin-management.js:193:12
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:604:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
    at Main.registerPluginControls (/Users/noahjchampion/.atom/packages/minimap/lib/mixins/plugin-management.js:192:53)
    at Main.registerPlugin (/Users/noahjchampion/.atom/packages/minimap/lib/mixins/plugin-management.js:70:12)
    at Object.module.exports.consumeMinimapServiceV1 (/Users/noahjchampion/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace.coffee:15:14)
    at Provider.module.exports.Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "autocomplete-wordpress-hooks",
      "css-specificity",
      "flexbox-snippets",
      "wp-phptidy",
      "archive-view",
      "autocomplete-atom-api",
      "autocomplete-html",
      "autoflow",
      "background-tips",
      "bracket-matcher",
      "deprecation-cop",
      "dev-live-reload",
      "encoding-selector",
      "wrap-guide",
      "whitespace",
      "welcome",
      "timecop",
      "styleguide",
      "snippets",
      "open-on-github",
      "metrics",
      "markdown-preview",
      "line-ending-selector",
      "language-yaml",
      "language-xml",
      "language-toml",
      "language-shellscript",
      "language-ruby-on-rails",
      "language-ruby",
      "language-python",
      "language-perl",
      "language-objective-c",
      "language-mustache",
      "language-make",
      "language-java",
      "language-hyperlink",
      "language-go",
      "language-gfm",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "language-c",
      "find-and-replace"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
css-snippets, v0.9.0
fonts, v1.1.0
icon-fonts, v1.10.2
letter-spacing, v0.3.1
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
wordpress-api, v1.2.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
Hmm, weird, the `find-and-replace` package should always be loaded as it's a bundled package, so reading its metadata should always be possible when `minimap-find-and-replace` is activated.

Did you do something with `find-and-replace`, like deactivating it or else?

**Comment by ShadowLNC** [comment]
I disabled find-and-replace to reproduce a bug in settings-view, and encountered this error on Atom start.
