### ISSUE TITLE
Uncaught TypeError: _ref1.is is not a function

### ISSUE THREAD

**Issue by alvinthomas** [atom-minimap/minimap-find-and-replace#22]
[Enter steps to reproduce:]

1. Typed Ctrl-F to start standard find-and-replace
2. Error thrown - could not find new instances of text nor replace

**Atom**: 1.16.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 7 Enterprise 
**Thrown From**: [minimap-find-and-replace](https://github.com/atom-minimap/minimap-find-and-replace) package 4.5.2

### Stack Trace

Uncaught TypeError: _ref1.is is not a function

```
At /C:/Users/athom102/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace-binding.coffee:128

TypeError: _ref1.is is not a function
    at MinimapFindAndReplaceBinding.module.exports.MinimapFindAndReplaceBinding.findViewIsVisible (/packages/minimap-find-and-replace/lib/minimap-find-and-replace-binding.coffee:73:54)
    at MinimapFindAndReplaceBinding.module.exports.MinimapFindAndReplaceBinding.createDecoration (/packages/minimap-find-and-replace/lib/minimap-find-and-replace-binding.coffee:56:20)
    at /packages/minimap-find-and-replace/lib/minimap-find-and-replace-binding.coffee:46:48
    at Array.forEach (native)
    at MinimapFindAndReplaceBinding.module.exports.MinimapFindAndReplaceBinding.discoverMarkers (/packages/minimap-find-and-replace/lib/minimap-find-and-replace-binding.coffee:46:27)
    at Object.discoverMarkers (/packages/minimap-find-and-replace/lib/minimap-find-and-replace.coffee:85:13)
    at /packages/minimap-find-and-replace/lib/minimap-find-and-replace.coffee:35:36)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -2:32.4.0 core:copy (input.hidden-input)
     -2:32.2.0 find-and-replace:show (input.hidden-input)
     -2:24.4.0 core:paste (input.hidden-input)
     -2:21.4.0 core:backspace (input.hidden-input)
     -2:20.3.0 core:paste (input.hidden-input)
     -2:19.2.0 core:backspace (input.hidden-input)
  2x -2:18.7.0 core:move-left (input.hidden-input)
     -2:13.9.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui.find-visible)
     -1:50.9.0 editor:consolidate-selections (input.hidden-input)
     -1:50.9.0 core:cancel (input.hidden-input)
     -1:48.3.0 core:save (input.hidden-input)
     -1:41.2.0 find-and-replace:show (input.hidden-input)
     -0:43.4.0 core:confirm (input.hidden-input)
     -0:22.8.0 editor:consolidate-selections (input.hidden-input)
     -0:22.8.0 core:cancel (input.hidden-input)
     -0:21.6.0 find-and-replace:show (input.hidden-input)
```

### Non-Core Packages

```
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
file-icons 2.0.15 
gaia-dark-syntax 2.0.0 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
git-plus 7.3.0 
highlight-selected 0.12.0 
language-latex 1.0.0 
language-r 0.4.1 
language-stata 0.4.0 
latex 0.42.3 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.5.0 
nefelio-dark-syntax 2.0.0 
script 3.14.1 
seti-syntax 1.1.2 
seti-ui 1.6.1 
tinacious-design-syntax 1.0.0 
```

**Comment by paulmederos** [comment]
@alvinthomas I ran into the same issue, and found that upgrading to `4.5.2` made the error go away 🤞

**Comment by paulmederos** [comment]
@alvinthomas I found that upgrading `minimap` to `4.27.1` made this error go away 🤞

**Comment by alvinthomas** [comment]
Thanks. I've had the "failed to load" issue with updates for a while now. Just resolved it (after removing seti-ui) and upgraded to the latest minimap version.
