### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getActiveMinimap' of undefined

### ISSUE THREAD

**Issue by aadamsx** [atom-minimap/minimap-find-and-replace#3]
Uncaught TypeError: Cannot read property 'getActiveMinimap' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: [minimap-find-and-replace](https://github.com/abe33/minimap-find-and-replace) package, v3.1.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Users/aadams/.atom/packages/minimap-find-and-replace/lib/minimap-find-results-view.coffee:21

TypeError: Cannot read property 'getActiveMinimap' of undefined
  at MinimapFindResultsView.getMinimap (/Users/aadams/.atom/packages/minimap-find-and-replace/lib/minimap-find-results-view.coffee:21:34)
  at MinimapFindResultsView.markersUpdated (/Users/aadams/.atom/packages/minimap-find-and-replace/lib/minimap-find-results-view.coffee:24:18)
  at /Users/aadams/.atom/packages/minimap-find-and-replace/lib/minimap-find-results-view.coffee:1:1
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at FindModel.module.exports.FindModel.destroyAllMarkers (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-model.js:244:20)
  at FindModel.module.exports.FindModel.activePaneItemChanged (/Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-model.js:50:12)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/find-and-replace/lib/find-model.js:3:61
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:250:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:314:21)
  at tabs-tab.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:184:24)
  at space-pen-ul.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

/cc @atom/core

**Comment by fundon** [comment]
Update the Atom and Minimap-find-and-replace.
