### ISSUE TITLE
Uncaught TypeError: this.bindingsById.values is not a function (toogling find-and-replace)

### ISSUE THREAD

**Issue by Narann** [atom-minimap/minimap-find-and-replace#43]
Hello,

I get an error when I toggle "find-and-replace" checkbox in minimap (on the side): 

![image](https://user-images.githubusercontent.com/659708/102067822-f0bdfa80-3dfb-11eb-86e0-20ad38f8d6dc.png)

**Atom**: 1.52.0 x64
**Electron**: 6.1.12
**OS**: Debian GNU/Linux
**Thrown From**: [minimap-find-and-replace](https://github.com/atom-minimap/minimap-find-and-replace) package 5.0.6

### Stack Trace

Uncaught TypeError: this.bindingsById.values is not a function

```
At /home/narann/.atom/packages/minimap-find-and-replace/lib/minimap-find-and-replace.js:90

TypeError: this.bindingsById.values is not a function
    at Object.changeVisible (/packages/minimap-find-and-replace/lib/minimap-find-and-replace.js:90:38)
    at Object.setOnChangeVisibility (/packages/minimap-find-and-replace/lib/minimap-find-and-replace.js:74:9)
    at /packages/minimap-find-and-replace/lib/minimap-find-and-replace.js:42:9
    at Provider.provide (/usr/share/atom/resources/app/static/<embedded>:14:1086069)
    at ServiceHub.consume (/usr/share/atom/resources/app/static/<embedded>:11:3180054)
    at Object.initializeServiceAPI (/packages/minimap-find-and-replace/lib/minimap-find-and-replace.js:41:28)
    at Object.activatePlugin (/packages/minimap-find-and-replace/lib/minimap-find-and-replace.js:37:8)
    at Main.activatePlugin (/packages/minimap/lib/mixins/plugin-management.js:187:12)
    at Main.updatesPluginActivationState (/packages/minimap/lib/mixins/plugin-management.js:171:14)
    at /packages/minimap/lib/mixins/plugin-management.js:241:12
    at /usr/share/atom/resources/app/static/<embedded>:11:335145
    at /usr/share/atom/resources/app/static/<embedded>:11:335326
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1190511)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191952)
    at Config.emitChangeEvent (/usr/share/atom/resources/app/static/<embedded>:11:337814)
    at Config.setRawValue (/usr/share/atom/resources/app/static/<embedded>:11:335054)
    at Config.set (/usr/share/atom/resources/app/static/<embedded>:11:330848)
    at Main.togglePluginActivation (/packages/minimap/lib/mixins/plugin-management.js:126:19)
    at action (/packages/minimap/lib/minimap-quick-settings-element.js:212:33)
    at /packages/minimap/lib/minimap-quick-settings-element.js:221:7)
```

### Commands

```
     -0:30 find-and-replace:show (input.hidden-input)
     -0:28.5.0 editor:consolidate-selections (input.hidden-input)
     -0:28.5.0 core:cancel (input.hidden-input)
     -0:28.3.0 editor:consolidate-selections (input.hidden-input)
     -0:28.3.0 core:cancel (input.hidden-input)
     -0:27.1.0 find-and-replace:show (input.hidden-input)
     -0:24.4.0 editor:consolidate-selections (input.hidden-input)
     -0:24.4.0 core:cancel (input.hidden-input)
     -0:24.2.0 editor:consolidate-selections (input.hidden-input)
     -0:24.2.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
cursor-history 0.14.0 
highlight-bad-chars 2.0.0 
highlight-selected 0.17.0 
minimap 4.35.7 
minimap-cursorline 1.0.0 
minimap-find-and-replace 5.0.6 
minimap-git-diff 4.3.4 
minimap-highlight-selected 4.6.3 
wordcount 3.2.0 
```

Feel free to ask for more information.

Keep the good work!

**Comment by UziTech** [comment]
Thanks for reporting this bug. :100:
