### ISSUE TITLE
Uncaught TypeError: Cannot read property 'decorationsById' of undefined

### ISSUE THREAD

**Issue by scott-wilson** [atom-minimap/minimap-find-and-replace#9]
[Enter steps to reproduce below:]

1. Open the Find/ Replace dialog (I used ctrl + f) with no files open.
2. Close the Find/ Replace dialog with Esc with no files open.

**Atom Version**: 1.0.7
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [minimap-find-and-replace](https://github.com/atom-minimap/minimap-find-and-replace) package, v4.2.2

### Stack Trace

Uncaught TypeError: Cannot read property 'decorationsById' of undefined

```
At C:\Users\scott.wilson\.atom\packages\minimap-find-and-replace\lib\minimap-find-results-view.coffee:19

TypeError: Cannot read property 'decorationsById' of undefined
    at MinimapFindResultsView.destroyDecorations (C:\Users\scott.wilson\.atom\packages\minimap-find-and-replace\lib\minimap-find-results-view.coffee:27:33)
    at MinimapFindResultsView.destroy (C:\Users\scott.wilson\.atom\packages\minimap-find-and-replace\lib\minimap-find-results-view.coffee:20:14)
    at MinimapFindAndReplaceBinding.module.exports.MinimapFindAndReplaceBinding.deactivate (C:\Users\scott.wilson\.atom\packages\minimap-find-and-replace\lib\minimap-find-and-replace-binding.coffee:86:15)
    at atom-workspace.<anonymous> (C:\Users\scott.wilson\.atom\packages\minimap-find-and-replace\lib\minimap-find-and-replace-binding.coffee:3:61)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\scott.wilson\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:241:29)
    at C:\Users\scott.wilson\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\scott.wilson\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\scott.wilson\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\scott.wilson\AppData\Local\atom\app-1.0.7\resources\app.asar\src\window-event-handler.js:177:20)
```

### Commands

```
     -0:08.8.0 find-and-replace:show (atom-pane.pane.active)
     -0:07.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:07.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
autocomplete-plus-python-jedi, v0.3.6
color-picker, v2.0.11
ctags-status, v1.3.3
file-icons, v1.6.3
language-batch, v0.3.3
language-mel, v0.1.2
language-tcl, v0.1.2
linter, v1.4.2
linter-flake8, v1.6.1
minimap, v4.12.3
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-selection, v4.3.0

# Dev
No dev packages
```

**Comment by abe33** [comment]
I just released a new version, can you tell me if you still get the error after the update?

**Comment by scott-wilson** [comment]
All is good now, thanks!
